version: '1'

services:
  node-app:
    build: .
    image: NextHandleBackend
    environment:
      - MONGODB_URL=''
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/NextHandle
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
