swagger: '2.0'
info:
  version: 1.0.0
  title: NextHandle
  description: Api for next handle
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: https://nexthandle-backend.herokuapp.com
basePath: "/api/v1"
tags:
- name: Users
  description: API for users in the system
schemes:
- http
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Bearer:
    type: apiKey
    description: "Value: Bearer {jwt}"
    name: Authorization
    in: header
security:
- Bearer: []  
paths:
  "/users/create":
    post:
      tags:
      - Users
      description: Create new user in system
      parameters:
      - name: user
        in: body
        description: User that we want to create
        schema:
          "$ref": "#/definitions/User"
      produces:
      - application/json
      responses:
        '200':
          description: New user is created
          schema:
            "$ref": "#/definitions/User"
    get:
      tags:
      - Users
      summary: Get all users in system
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Users"
  "/users/{userId}":
    parameters:
    - name: userId
      in: path
      required: true
      description: ID of user that we want to find
      type: string
    get:
      tags:
      - Users
      summary: Get user with given ID
      responses:
        '200':
          description: User is found
          schema:
            "$ref": "#/definitions/User"
    delete:
      summary: Delete user with given ID
      tags:
      - Users
      responses:
        '200':
          description: User is deleted
          schema:
            "$ref": "#/definitions/User"
    put:
      summary: Update user with give ID
      tags:
      - Users
      parameters:
      - name: user
        in: body
        description: User with new values of properties
        schema:
          "$ref": "#/definitions/User"
      responses:
        '200':
          description: User is updated
          schema:
            "$ref": "#/definitions/User"
definitions:
  User:
    required:
    - firstName
    - email
    - phoneNumber
    - userType
    - password
    properties:
      firstName:
        type: string
      email:
        type: string
        uniqueItems: true
      lastName:
        type: string
      password:
        type: string
      userType:
        type: string  
  Users:
    type: array
    "$ref": "#/definitions/User"